// Spec-driven/angular-sdd-web-postman-starter/ui-app/src/ui/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
  <main style="font-family: system-ui; padding:16px">
    <h1>Web Postman</h1>
    <nav><a routerLink="/">Builder</a> | <a routerLink="/collections">Collections</a></nav>
    <router-outlet></router-outlet>
  </main>
  `
})
export class AppComponent {}

// Spec-driven/react-sdd-web-postman-starter/ui-app/src/ui/App.tsx
import React from 'react';
import { Outlet, Link } from 'react-router-dom';

export default function App() {
  return (
    <main style={{ fontFamily: 'system-ui', padding: 16 }}>
      <h1>Web Postman</h1>
      <nav style={{ marginBottom: 12 }}>
        <Link to="/">Builder</Link> | <Link to="/collections">Collections</Link>
      </nav>
      <Outlet />
    </main>
  );
}
