// Spec-driven/angular-sdd-web-postman-starter/ui-app/src/ui/builder.component.ts
import { Component, signal } from '@angular/core';
import { HttpClient, provideHttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-builder',
  imports: [FormsModule],
  providers: [provideHttpClient()],
  template: `
  <section>
    <input placeholder="URL" [(ngModel)]="url" />
    <select [(ngModel)]="method">
      <option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option>
    </select>
    <button (click)="send()">Send</button>
    <pre *ngIf="resp() as r">{{ r | json }}</pre>
  </section>
  `
})
export class BuilderComponent {
  url = 'http://localhost:4000/echo';
  method: any = 'GET';
  resp = signal<any>(null);
  constructor(private http: HttpClient) {}
  async send() {
    const body = this.method === 'GET' ? undefined : '';
    const out = await this.http.post('/proxy', { method: this.method, url: this.url, headers: {}, body }).toPromise();
    this.resp.set(out);
  }
}

// Spec-driven/react-sdd-web-postman-starter/ui-app/src/ui/Builder.tsx
import React from 'react';
import { useState } from 'react';

export default function Builder() {
  const [url, setUrl] = useState('http://localhost:4000/echo');
  const [method, setMethod] = useState('GET');
  const [resp, setResp] = useState<any>(null);

  async function send() {
    const body = method === 'GET' ? undefined : '';
    const r = await fetch('/proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ method, url, headers: {}, body })
    });
    setResp(await r.json());
  }

  return (
    <section>
      <input placeholder="URL" value={url} onChange={e => setUrl(e.target.value)} data-testid="url-input" />
      <select value={method} onChange={e => setMethod(e.target.value)} data-testid="method-select">
        <option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option>
      </select>
      <button onClick={send} data-testid="send-btn">Send</button>
      <pre data-testid="resp-pre">{resp ? JSON.stringify(resp, null, 2) : ''}</pre>
    </section>
  );
}
